[[overview]]

This section will provide you with a detailed overview of the out of hte box Spring Cloud Stream Applications.
It assumes familiarity with general Spring Cloud Stream concepts, which can be found in the Spring Cloud Stream https://cloud.spring.io/spring-cloud-static/spring-cloud-stream/{scst-core-version}/[reference documentation].

== Introduction

These Spring Cloud Stream Applications provide you with out-of-the-box Spring Cloud Stream utility applications that you can run independently or with Spring Cloud Data Flow.

They include:

* connectors (sources, processors, and sinks) for a variety of middleware technologies including message brokers, storage (relational, non-relational, filesystem);
* adapters for various network protocols;
* generic processors that can be customized via https://docs.spring.io/spring/docs/4.2.x/spring-framework-reference/html/expressions.html[Spring Expression Language (SpEL)] or scripting.

You can find a detailed listing of all the applications and their options in the <<starters,corresponding>> section of this guide.

=== Pre-built applications

_Out-of-the-box applications_ are Spring Boot applications that include a Binder implementation on top of the basic logic of the app (a function for e.g.) - a fully functional uber-jar.
These https://docs.spring.io/spring-boot/docs/current-SNAPSHOT/reference/html/getting-started.html#getting-started-first-application-executable-jar[uber-jar's] include minimal code required to execute standalone.
For each function application, the project provides a prebuilt version for Apache Kafka and Rabbit MQ Binders.

[NOTE]
Prebuilt applications are generated according to the https://github.com/spring-cloud/spring-cloud-app-starters-maven-plugins/tree/master/spring-cloud-stream-app-maven-plugin[stream apps generator maven plugin].

[[classification]]
=== Classification

Based on their target application type, they can be either:

* a _source_ that connects to an external resource to poll and receive data that is published to the default "output" channel;
* a _processor_ that receives data from an "input" channel and processes it, sending the result on the default "output" channel;
* a _sink_ that connects to an external resource to send the received data to the default "input" channel.

The prebuilt applications follow a naming convention: `<functionality>-<type>-<binder>`. For example, `rabbit-sink-kafka` is a _Rabbit sink_ using the Kafka binder that is running with Kafka as the middleware.

==== Maven and Docker access

Core functionality of the apps are available as functions.
They are provided as Maven artifacts in the https://github.com/spring-projects/spring-framework/wiki/Spring-Artifactory[Spring repositories]. You can add them as dependencies to your application, as follows:

[source,xml]
----
<dependency>
  <groupId>io.pivotal.java.function</groupId>
  <artifactId>jdbc-supplier</artifactId>
  <version>1.0.0.BUILD-SNAPSHOT</version>
</dependency>
----

Prebuilt applications are available as Maven artifacts.
You can download the executable jar artifacts from the Spring Maven repositories.
The root directory of the Maven repository that hosts release versions is https://repo.spring.io/release/org/springframework/cloud/stream/app/.
From there you can navigate to the latest released version of a specific app, for example link:https://repo.spring.io/release/org/springframework/cloud/stream/app/log-sink-rabbit/2.0.2.RELEASE/log-sink-rabbit-1.1.1.RELEASE.jar[log-sink-rabbit-2.0.2.RELEASE.jar].
Use the link:https://repo.spring.io/milestone/org/springframework/cloud/stream/app[Milestone] and link:https://repo.spring.io/snapshot/org/springframework/cloud/stream/app[Snapshot] repository locations for Milestone and Snapshot executable jar artifacts.

The Docker versions of the applications are available in Docker Hub, at `https://hub.docker.com/r/springcloudstream/`.
Naming and versioning follows the same general conventions as Maven, e.g.

[source,bash]
----
docker pull springcloudstream/cassandra-sink-kafka
----

will pull the _latest_ Docker image of the _Cassandra sink_ with the Kafka binder.

==== Building the Artifacts

You can build the project and generate the artifacts (including the prebuilt applications) on your own.
This is useful if you want to deploy the artifacts locally or add additional features.

First, you need to generate the prebuilt applications.
This is done by running the application generation Maven plugin.
You can do so by simply invoking the maven build.
If you are at the root of the repository, [steam-applications](https://github.com/spring-cloud-stream-app-starters/stream-applications), then doing a maven build will generate the entire binder based apps.
If you don't want to do that and instead only are interested in a certain app, then cd into the right module and invoke the build from there.

[source,bash]
----
mvn clean package
----

This will generate the apps. By default, the generated projects are placed under a directory called `apps`.
There you can find the binder based applications which you can then build and run.

=== Patching Pre-built Applications

If you're looking to patch the pre-built applications to accommodate the addition of new dependencies, you can use the following example as the reference.
Let's review the steps to add `mysql` driver to `jdbc-sink` application.

* Clone the GitHub repository https://github.com/spring-cloud-stream-app-starters/stream-applications
* Open it in an IDE and make the necessary changes in the right generator proejct. The repository is organized as `source-apps-generator`, `sink-apps-generator` and `processor-apps-generator`.
  Find the module that you want to patch and make the changes. For e.g. add the following to the generator plugin's configuration in the pom.xml

[source,xml]
----
<dependencies>
  <dependency>
    <groupId>mysql</groupId>
    <artifactId>mysql-connector-java</artifactId>
    <version>5.1.37</version>
  </dependency>
  <dependency>
    <groupId>org.springframework.cloud</groupId>
    <artifactId>spring-cloud-stream-binder-rabbit</artifactId>
  </dependency>
</dependencies>
----

* Generate the binder based apps as specified above and build the apps.
